import { MenuItem, ReviewItem, GalleryItem, CoffeeFeature } from './types';

export const BUSINESS_INFO = {
  name: 'Coffee Land',
  tagline: 'Good Coffee. Good Food. Good Mornings.',
  shortDescription: 'A neighborhood coffee destination in Brooklyn for carefully crafted coffee, satisfying breakfast, and relaxed everyday moments.',
  metaDescription: 'Coffee Land is a Brooklyn neighborhood café at 450 Grand Ave serving coffee, breakfast and takeout.',
  address: '450 Grand Ave, Brooklyn, NY 11238, United States',
  shortAddress: '450 Grand Ave · Brooklyn, NY',
  street: '450 Grand Ave',
  neighborhood: 'Clinton Hill / Bedford-Stuyvesant border, Brooklyn',
  city: 'Brooklyn',
  state: 'NY',
  zip: '11238',
  country: 'United States',
  phone: '+1 347-294-0224',
  phoneClean: '+13472940224',
  rating: 4.6,
  reviewCount: 127,
  priceRange: '$1–$10',
  pricePerPerson: '$1–$10 per person',
  status: 'Open · Closes at 6:00 PM',
  services: {
    dineIn: true,
    takeout: true,
    delivery: false,
  },
  plusCode: 'M2MQ+57 Brooklyn, New York, United States',
  googleMapsDirections: 'https://www.google.com/maps/dir/?api=1&destination=450+Grand+Ave,+Brooklyn,+NY+11238',
  googleMapsPlace: 'https://www.google.com/maps/search/?api=1&query=Coffee+Land+450+Grand+Ave+Brooklyn+NY+11238',
};

export const FEATURED_COFFEES: CoffeeFeature[] = [
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    roastNotes: 'Rich espresso, velvety microfoam, cocoa dusting',
    description: 'A classic balanced cup with a dense, creamy foam layer over double-extracted espresso.',
    temp: 'Hot',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=85',
    accent: 'Double Shot + Silky Microfoam',
  },
  {
    id: 'latte',
    name: 'Latte',
    roastNotes: 'Smooth, comforting, balanced milk sweetness',
    description: 'Smooth espresso gently folded with steamed whole milk or oat milk with subtle natural caramel notes.',
    temp: 'Hot / Iced',
    image: 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?auto=format&fit=crop&w=800&q=85',
    accent: 'Whole Milk / Oat Milk Options',
  },
  {
    id: 'espresso',
    name: 'Espresso',
    roastNotes: 'Bold crema, dark chocolate aroma, bright citrus finish',
    description: 'Carefully pulled single origin blend with thick golden crema and a clean, lingering finish.',
    temp: 'Hot',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=85',
    accent: 'Signature Roast Extraction',
  },
  {
    id: 'cold-cappuccino',
    name: 'Cold Cappuccino',
    roastNotes: 'Chilled espresso, aerated cold froth, crisp finish',
    description: 'A refreshing Brooklyn favorite with chilled espresso topped with thick velvety cold milk cloud.',
    temp: 'Iced',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=85',
    accent: 'Velvety Cold Foam Layer',
  },
  {
    id: 'iced-coffee',
    name: 'Iced Coffee',
    roastNotes: 'Slow brewed, deeply refreshing, clean & crisp',
    description: 'Brewed fresh daily over ice with clear bright notes and a smooth, low-acidity profile.',
    temp: 'Iced',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=85',
    accent: 'Daily Fresh Chilled Brew',
  },
  {
    id: 'matcha-latte',
    name: 'Matcha Latte',
    roastNotes: 'Ceremonial grade green tea, creamy steamed milk',
    description: 'Whisked premium Japanese green tea paired with steamed milk for clean energy and rich herbal depth.',
    temp: 'Hot / Iced',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=85',
    accent: 'Ceremonial Grade Matcha',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // BREAKFAST
  {
    id: 'avocado-toast',
    name: 'Avocado Toast',
    category: 'breakfast',
    description: 'Toasted rustic artisanal sourdough topped with fresh mashed avocado, microgreens, sea salt flakes, and a touch of red pepper spice.',
    priceNote: 'Ask in store',
    isHouseFavorite: true,
    isPopular: true,
    dietary: ['House Favorite', 'Vegetarian', 'Fresh Daily'],
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'breakfast-sandwich',
    name: 'Morning Egg & Cheese Toast',
    category: 'breakfast',
    description: 'Warm toasted brioche bread with fluffy farm eggs, melted sharp cheddar, and seasoned herbs.',
    priceNote: 'Ask in store',
    isPopular: true,
    dietary: ['Warm & Savory', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'granola-yogurt-bowl',
    name: 'Granola & Berry Parfait',
    category: 'breakfast',
    description: 'Thick creamy Greek yogurt layered with toasted crunchy oat granola, fresh seasonal berries, and wildflower honey.',
    priceNote: 'Ask in store',
    dietary: ['Vegetarian', 'Fresh Fruit'],
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=85',
  },

  // COFFEE
  {
    id: 'house-cappuccino',
    name: 'Signature Cappuccino',
    category: 'coffee',
    description: 'Equal parts rich espresso, steamed milk, and silky thick foam with a gentle dusted finish.',
    priceNote: 'Ask in store',
    isPopular: true,
    dietary: ['Hot', 'Oat/Whole Milk'],
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'house-latte',
    name: 'Classic Café Latte',
    category: 'coffee',
    description: 'Double shot of rich house espresso combined with silky micro-steamed milk and delicate latte art.',
    priceNote: 'Ask in store',
    isPopular: true,
    dietary: ['Hot / Iced'],
    image: 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'house-espresso',
    name: 'Double Espresso',
    category: 'coffee',
    description: 'Direct pulled double shot with thick hazelnut crema, notes of roasted cocoa and toasted almond.',
    priceNote: 'Ask in store',
    dietary: ['Hot', 'Single Origin Blend'],
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'americano',
    name: 'Americano',
    category: 'coffee',
    description: 'Espresso stretched over hot filtered water, preserving a clean aromatic cup profile.',
    priceNote: 'Ask in store',
    dietary: ['Hot / Iced'],
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'macchiato',
    name: 'Espresso Macchiato',
    category: 'coffee',
    description: 'Bold double espresso marked with a delicate dollop of warm textured milk foam.',
    priceNote: 'Ask in store',
    dietary: ['Hot'],
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=800&q=85',
  },

  // COLD DRINKS
  {
    id: 'cold-cappuccino-item',
    name: 'Cold Froth Cappuccino',
    category: 'cold-drinks',
    description: 'Iced espresso layered beneath dense, cloud-like cold aerated foam.',
    priceNote: 'Ask in store',
    isPopular: true,
    dietary: ['Iced', 'House Special'],
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'iced-brew',
    name: 'Craft Iced Coffee',
    category: 'cold-drinks',
    description: 'Crisp cold brew served over crystal clear ice with a smooth, refreshing finish.',
    priceNote: 'Ask in store',
    dietary: ['Iced'],
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'iced-matcha',
    name: 'Iced Matcha Latte',
    category: 'cold-drinks',
    description: 'Vibrant shade-grown ceremonial matcha whisked and poured over ice and creamy milk.',
    priceNote: 'Ask in store',
    dietary: ['Iced', 'Antioxidant Rich'],
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'lemonade-refresher',
    name: 'House Citrus Refresher',
    category: 'cold-drinks',
    description: 'Freshly squeezed citrus lemonade infused with subtle mint and sparkling water.',
    priceNote: 'Ask in store',
    dietary: ['Iced', 'Refreshing'],
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=85',
  },

  // TEA
  {
    id: 'ceremonial-matcha',
    name: 'Ceremonial Matcha Tea',
    category: 'tea',
    description: 'Finely ground Japanese green tea whisked with pure hot water for traditional clean clarity.',
    priceNote: 'Ask in store',
    dietary: ['Hot / Iced'],
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'chai-latte',
    name: 'Spiced Chai Latte',
    category: 'tea',
    description: 'Slow-simmered black tea infused with cardamom, cinnamon, clove, ginger, and steamed milk.',
    priceNote: 'Ask in store',
    dietary: ['Hot / Iced', 'Spiced'],
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'loose-leaf-tea',
    name: 'Artisan Herbal & Black Teas',
    category: 'tea',
    description: 'Selection of organic whole-leaf teas: Earl Grey, Jasmine Green, Chamomile, and Peppermint.',
    priceNote: 'Ask in store',
    dietary: ['Hot', 'Organic Selection'],
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=800&q=85',
  },

  // BAKERY
  {
    id: 'butter-croissant',
    name: 'Butter Croissant',
    category: 'bakery',
    description: 'Flaky golden laminated pastry baked fresh daily with pure European butter.',
    priceNote: 'Ask in store',
    isPopular: true,
    dietary: ['Baked Daily', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'chocolate-croissant',
    name: 'Pain au Chocolat',
    category: 'bakery',
    description: 'Crisp layered pastry wrapped around double batons of rich dark bittersweet chocolate.',
    priceNote: 'Ask in store',
    dietary: ['Baked Daily', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=800&q=85',
  },
  {
    id: 'cinnamon-pastry',
    name: 'Morning Cinnamon Swirl',
    category: 'bakery',
    description: 'Caramelized pastry swirl infused with warm Ceylon cinnamon and raw cane sugar.',
    priceNote: 'Ask in store',
    dietary: ['Baked Daily', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=85',
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Artisan Espresso Extraction',
    category: 'Coffee',
    src: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=1200&q=85',
    alt: 'Freshly extracted espresso with thick hazelnut crema at Coffee Land Brooklyn',
    aspect: 'square',
    caption: 'Double shot extraction pulled fresh on Grand Ave.',
  },
  {
    id: 'gal-2',
    title: 'Signature Avocado Toast',
    category: 'Breakfast',
    src: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?auto=format&fit=crop&w=1200&q=85',
    alt: 'House avocado toast on rustic toasted sourdough with microgreens',
    aspect: 'portrait',
    caption: 'Our signature avocado toast, seasoned to perfection.',
  },
  {
    id: 'gal-3',
    title: 'Warm Café Morning Ambiance',
    category: 'Interior',
    src: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=85',
    alt: 'Warm Brooklyn café seating with natural morning light and cozy wood tables',
    aspect: 'wide',
    caption: 'Relaxed seating designed for morning calm and casual breaks.',
  },
  {
    id: 'gal-4',
    title: 'Silky Microfoam Cappuccino',
    category: 'Coffee',
    src: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=1200&q=85',
    alt: 'Freshly poured cappuccino with smooth microfoam in ceramic cup',
    aspect: 'landscape',
    caption: 'Handcrafted latte art with carefully steamed milk.',
  },
  {
    id: 'gal-5',
    title: 'Fresh Baked Morning Pastries',
    category: 'Food',
    src: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1200&q=85',
    alt: 'Golden flaky butter croissants and breakfast pastries on bakery counter',
    aspect: 'portrait',
    caption: 'Crisp, golden pastries delivered fresh every morning.',
  },
  {
    id: 'gal-6',
    title: 'Chilled Refreshers & Iced Brews',
    category: 'Atmosphere',
    src: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1200&q=85',
    alt: 'Cold brew coffee with clear ice cubes on wooden tabletop',
    aspect: 'square',
    caption: 'Refreshing cold drinks for sunny Brooklyn afternoons.',
  },
  {
    id: 'gal-7',
    title: 'Ceremonial Matcha Preparation',
    category: 'Coffee',
    src: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=1200&q=85',
    alt: 'Vibrant green matcha latte layered with milk over ice',
    aspect: 'landscape',
    caption: 'Rich matcha latte whisked with organic ceremonial tea.',
  },
  {
    id: 'gal-8',
    title: 'Brooklyn Neighborhood Vibe',
    category: 'Atmosphere',
    src: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=85',
    alt: 'Cozy café corner with books, coffee mugs and urban street view',
    aspect: 'portrait',
    caption: 'A welcoming corner in Brooklyn to sit, read, or catch up.',
  },
];

export const REVIEWS_LIST: ReviewItem[] = [
  {
    id: 'rev-1',
    author: 'Elena Rostova',
    rating: 5,
    date: 'Recent Google Review',
    relativeTime: '2 weeks ago',
    text: 'One of the best neighborhood coffee spots in the area! The coffee is consistently smooth and rich, and their avocado toast is absolutely delicious. Warm, welcoming staff every single morning.',
    verified: true,
    highlight: 'Consistently smooth & rich coffee',
  },
  {
    id: 'rev-2',
    author: 'Marcus Chen',
    rating: 5,
    date: 'Recent Google Review',
    relativeTime: '1 month ago',
    text: 'Great cappuccino, chill atmosphere, and very fair prices for Brooklyn ($1-$10). Perfect place to grab takeout on the way to the subway or sit down for a relaxed morning.',
    verified: true,
    highlight: 'Great cappuccino & chill atmosphere',
  },
  {
    id: 'rev-3',
    author: 'Sarah Jenkins',
    rating: 5,
    date: 'Recent Google Review',
    relativeTime: '1 month ago',
    text: 'The avocado toast here is a must-try. Everything is fresh, clean, and made with care. Love having Coffee Land as our local go-to café on Grand Ave.',
    verified: true,
    highlight: 'Avocado toast is a must-try',
  },
  {
    id: 'rev-4',
    author: 'David Morales',
    rating: 4,
    date: 'Recent Google Review',
    relativeTime: '2 months ago',
    text: 'Solid quality coffee, fast takeout service, and great pastry selection. Super friendly barista team. Highly recommended if you are in the neighborhood.',
    verified: true,
    highlight: 'Fast takeout service & friendly team',
  },
];

export const QUICK_NAV_LINKS = [
  { name: 'Home', href: '#hero' },
  { name: 'About', href: '#about' },
  { name: 'Menu', href: '#menu' },
  { name: 'Reviews', href: '#reviews' },
  { name: 'Gallery', href: '#gallery' },
  { name: 'Location', href: '#location' },
];
